// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05973cMkAo54VjVdQrAzlqM9t0nLt5aI',
    appId: '1:547490552512:web:e1a1ae80bf6010894bab25',
    messagingSenderId: '547490552512',
    projectId: 'weedeyes-3d4ca',
    authDomain: 'weedeyes-3d4ca.firebaseapp.com',
    databaseURL: 'https://weedeyes-3d4ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weedeyes-3d4ca.appspot.com',
    measurementId: 'G-2CRVDZ8G59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vCbeYoUg9VjMUgxRsNLuCDvn2BzKcpY',
    appId: '1:547490552512:android:4da2b790717192c14bab25',
    messagingSenderId: '547490552512',
    projectId: 'weedeyes-3d4ca',
    databaseURL: 'https://weedeyes-3d4ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weedeyes-3d4ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWl-J8qipIruAPJiZz5gN8Ixmc7dfrRw',
    appId: '1:547490552512:ios:c7a93d67a1bef3f54bab25',
    messagingSenderId: '547490552512',
    projectId: 'weedeyes-3d4ca',
    databaseURL: 'https://weedeyes-3d4ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weedeyes-3d4ca.appspot.com',
    iosBundleId: 'com.example.weedeyes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWl-J8qipIruAPJiZz5gN8Ixmc7dfrRw',
    appId: '1:547490552512:ios:f924c56e7a7ef3744bab25',
    messagingSenderId: '547490552512',
    projectId: 'weedeyes-3d4ca',
    databaseURL: 'https://weedeyes-3d4ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weedeyes-3d4ca.appspot.com',
    iosBundleId: 'com.example.weedeyes.RunnerTests',
  );
}
